// Undercover word pairs: closely related but distinct concepts
export const PAIR_PACKS = {
  en: [
    ['Sea', 'Lake'], ['Coffee', 'Tea'], ['Guitar', 'Ukulele'], ['Pizza', 'Pie'], ['Wedding', 'Funeral'],
    ['Doctor', 'Nurse'], ['Snow', 'Rain'], ['Bus', 'Tram'], ['Beard', 'Moustache'], ['River', 'Stream'],
    ['Butter', 'Margarine'], ['Violin', 'Viola'], ['Crocodile', 'Alligator'], ['Frog', 'Toad'], ['Butterfly', 'Moth'],
    ['Donkey', 'Mule'], ['Lemon', 'Lime'], ['Orange', 'Tangerine'], ['Sweater', 'Cardigan'], ['Sandals', 'Flip-Flops'],
    ['Hat', 'Cap'], ['Novel', 'Short Story'], ['Movie', 'TV Series'], ['Painting', 'Drawing'], ['Sculpture', 'Statue'],
    ['Castle', 'Palace'], ['Village', 'Town'], ['City', 'Metropolis'], ['Ocean', 'Sea'], ['Hill', 'Mountain'],
    ['Puddle', 'Pond'], ['Cake', 'Cupcake'], ['Cookie', 'Biscuit'], ['Soup', 'Stew'], ['Juice', 'Smoothie'],
    ['Wine', 'Champagne'], ['Beer', 'Ale'], ['Whiskey', 'Brandy'], ['Sushi', 'Sashimi'], ['Burger', 'Sandwich'],
    ['Fries', 'Chips'], ['Doughnut', 'Bagel'], ['Muffin', 'Cupcake'], ['Waffle', 'Pancake'], ['Motorcycle', 'Moped'],
    ['Car', 'Van'], ['Truck', 'Lorry'], ['Bicycle', 'Tricycle'], ['Airplane', 'Glider'], ['Helicopter', 'Drone'],
    ['Ship', 'Boat'], ['Canoe', 'Kayak'], ['Submarine', 'Ship'], ['Train', 'Subway'], ['Football', 'Rugby'],
    ['Basketball', 'Volleyball'], ['Tennis', 'Badminton'], ['Boxing', 'Wrestling'], ['Judo', 'Karate'], ['Skiing', 'Snowboarding'],
    ['Swimming', 'Diving'], ['Cycling', 'Motorcycling'], ['Chess', 'Checkers'], ['Poker', 'Blackjack'], ['Darts', 'Archery'],
    ['Golf', 'Croquet'], ['Marathon', 'Sprint'], ['Gym', 'Yoga Studio'], ['Doctor', 'Dentist'], ['Nurse', 'Paramedic'],
    ['Teacher', 'Professor'], ['Lawyer', 'Judge'], ['Police Officer', 'Detective'], ['Firefighter', 'Paramedic'], ['Chef', 'Baker'],
    ['Waiter', 'Bartender'], ['Pilot', 'Flight Attendant'], ['Actor', 'Actress'], ['Singer', 'Rapper'], ['Painter', 'Illustrator'],
    ['Sculptor', 'Potter'], ['Photographer', 'Videographer'], ['Journalist', 'Blogger'], ['Author', 'Poet'], ['Scientist', 'Engineer'],
    ['Astronaut', 'Cosmonaut'], ['King', 'Emperor'], ['Queen', 'Empress'], ['Prince', 'Duke'], ['Knight', 'Samurai'],
    ['Wizard', 'Sorcerer'], ['Witch', 'Sorceress'], ['Vampire', 'Werewolf'], ['Ghost', 'Zombie'], ['Angel', 'Fairy'],
    ['Devil', 'Demon'], ['Dragon', 'Dinosaur'], ['Unicorn', 'Pegasus'], ['Mermaid', 'Siren'], ['Elf', 'Dwarf'],
    ['Giant', 'Ogre'], ['Robot', 'Cyborg'], ['Alien', 'Monster'], ['Superhero', 'Villain'], ['Spider', 'Scorpion'],
    ['Bee', 'Wasp'], ['Ant', 'Termite'], ['Butterfly', 'Dragonfly'], ['Snail', 'Slug'], ['Shark', 'Dolphin'],
    ['Whale', 'Dolphin'], ['Octopus', 'Squid'], ['Crab', 'Lobster'], ['Turtle', 'Tortoise'], ['Rabbit', 'Hare'],
    ['Fox', 'Wolf'], ['Cat', 'Kitten'], ['Dog', 'Puppy'], ['Horse', 'Pony'], ['Cow', 'Bull'],
    ['Goat', 'Sheep'], ['Duck', 'Goose'], ['Chicken', 'Turkey'], ['Eagle', 'Hawk'], ['Owl', 'Falcon'],
    ['Parrot', 'Cockatoo'], ['Penguin', 'Puffin'], ['Bear', 'Panda'], ['Lion', 'Tiger'], ['Monkey', 'Gorilla'],
    ['Elephant', 'Rhino'], ['Camel', 'Llama'], ['Deer', 'Elk'], ['Squirrel', 'Chipmunk'], ['Beach', 'Desert'],
    ['Forest', 'Jungle'], ['Volcano', 'Mountain'], ['Earthquake', 'Landslide'], ['Tornado', 'Hurricane'], ['Thunder', 'Lightning'],
    ['Fog', 'Mist'], ['Frost', 'Ice'], ['Sunrise', 'Sunset'], ['Autumn', 'Spring'], ['Winter', 'Summer'],
    ['Birthday', 'Anniversary'], ['Christmas', 'Thanksgiving'], ['Halloween', 'Carnival'], ['Prom', 'Wedding'], ['Interview', 'Exam'],
  ],
  ru: [
    ['Море', 'Озеро'], ['Чай', 'Кофе'], ['Гитара', 'Укулеле'], ['Пицца', 'Пирог'], ['Свадьба', 'Похороны'],
    ['Врач', 'Медсестра'], ['Снег', 'Дождь'], ['Автобус', 'Трамвай'], ['Борода', 'Усы'], ['Река', 'Ручей'],
    ['Масло', 'Маргарин'], ['Скрипка', 'Альт'], ['Крокодил', 'Аллигатор'], ['Лягушка', 'Жаба'], ['Бабочка', 'Моль'],
    ['Осёл', 'Мул'], ['Лимон', 'Лайм'], ['Апельсин', 'Мандарин'], ['Свитер', 'Кардиган'], ['Сандалии', 'Шлёпанцы'],
    ['Шапка', 'Кепка'], ['Роман', 'Повесть'], ['Фильм', 'Сериал'], ['Картина', 'Рисунок'], ['Скульптура', 'Статуя'],
    ['Замок', 'Дворец'], ['Деревня', 'Посёлок'], ['Город', 'Мегаполис'], ['Океан', 'Море'], ['Холм', 'Гора'],
    ['Лужа', 'Пруд'], ['Торт', 'Кекс'], ['Печенье', 'Пряник'], ['Суп', 'Борщ'], ['Сок', 'Компот'],
    ['Вино', 'Шампанское'], ['Пиво', 'Квас'], ['Водка', 'Самогон'], ['Блины', 'Оладьи'], ['Пельмени', 'Вареники'],
    ['Каша', 'Плов'], ['Шашлык', 'Стейк'], ['Пирожок', 'Чебурек'], ['Сырники', 'Блины'], ['Мотоцикл', 'Мопед'],
    ['Машина', 'Микроавтобус'], ['Грузовик', 'Фура'], ['Велосипед', 'Самокат'], ['Самолёт', 'Планер'], ['Вертолёт', 'Дрон'],
    ['Корабль', 'Лодка'], ['Каноэ', 'Байдарка'], ['Подводная лодка', 'Корабль'], ['Поезд', 'Электричка'], ['Футбол', 'Регби'],
    ['Баскетбол', 'Волейбол'], ['Теннис', 'Бадминтон'], ['Бокс', 'Борьба'], ['Дзюдо', 'Карате'], ['Лыжи', 'Сноуборд'],
    ['Плавание', 'Ныряние'], ['Велоспорт', 'Мотоспорт'], ['Шахматы', 'Шашки'], ['Покер', 'Блэкджек'], ['Дартс', 'Стрельба из лука'],
    ['Гольф', 'Крокет'], ['Марафон', 'Спринт'], ['Спортзал', 'Йога-студия'], ['Врач', 'Стоматолог'], ['Медсестра', 'Фельдшер'],
    ['Учитель', 'Профессор'], ['Юрист', 'Судья'], ['Полицейский', 'Следователь'], ['Пожарный', 'Спасатель'], ['Повар', 'Пекарь'],
    ['Официант', 'Бармен'], ['Пилот', 'Стюардесса'], ['Актёр', 'Актриса'], ['Певец', 'Рэпер'], ['Художник', 'Иллюстратор'],
    ['Скульптор', 'Гончар'], ['Фотограф', 'Видеограф'], ['Журналист', 'Блогер'], ['Писатель', 'Поэт'], ['Учёный', 'Инженер'],
    ['Космонавт', 'Астронавт'], ['Царь', 'Император'], ['Царица', 'Императрица'], ['Принц', 'Герцог'], ['Рыцарь', 'Самурай'],
    ['Волшебник', 'Колдун'], ['Ведьма', 'Колдунья'], ['Вампир', 'Оборотень'], ['Призрак', 'Зомби'], ['Ангел', 'Фея'],
    ['Чёрт', 'Демон'], ['Дракон', 'Динозавр'], ['Единорог', 'Пегас'], ['Русалка', 'Сирена'], ['Эльф', 'Гном'],
    ['Великан', 'Огр'], ['Робот', 'Киборг'], ['Пришелец', 'Монстр'], ['Супергерой', 'Злодей'], ['Паук', 'Скорпион'],
    ['Пчела', 'Оса'], ['Муравей', 'Термит'], ['Бабочка', 'Стрекоза'], ['Улитка', 'Слизень'], ['Акула', 'Дельфин'],
    ['Кит', 'Дельфин'], ['Осьминог', 'Кальмар'], ['Краб', 'Омар'], ['Черепаха', 'Игуана'], ['Кролик', 'Заяц'],
    ['Лиса', 'Волк'], ['Кошка', 'Котёнок'], ['Собака', 'Щенок'], ['Лошадь', 'Пони'], ['Корова', 'Бык'],
    ['Коза', 'Овца'], ['Утка', 'Гусь'], ['Курица', 'Индюк'], ['Орёл', 'Ястреб'], ['Сова', 'Сокол'],
    ['Попугай', 'Какаду'], ['Пингвин', 'Тупик'], ['Медведь', 'Панда'], ['Лев', 'Тигр'], ['Обезьяна', 'Горилла'],
    ['Слон', 'Носорог'], ['Верблюд', 'Лама'], ['Олень', 'Лось'], ['Белка', 'Бурундук'], ['Пляж', 'Пустыня'],
    ['Лес', 'Джунгли'], ['Вулкан', 'Гора'], ['Землетрясение', 'Оползень'], ['Торнадо', 'Ураган'], ['Гром', 'Молния'],
    ['Туман', 'Дымка'], ['Иней', 'Лёд'], ['Рассвет', 'Закат'], ['Осень', 'Весна'], ['Зима', 'Лето'],
    ['День рождения', 'Юбилей'], ['Новый год', 'Рождество'], ['Масленица', 'Пасха'], ['Выпускной', 'Свадьба'], ['Собеседование', 'Экзамен'],
  ],
}
