// Preset topic library (id, emoji, English/Russian/Spanish display names)
export const TOPIC_PRESETS = [
  { id: 'mixed', emoji: '🎲', en: 'Mixed', ru: 'Микс', es: 'Mezcla' },
  { id: 'animals', emoji: '🐘', en: 'Animals', ru: 'Животные', es: 'Animales' },
  { id: 'food-drink', emoji: '🍕', en: 'Food & Drink', ru: 'Еда и напитки', es: 'Comida y bebida' },
  { id: 'desserts', emoji: '🍰', en: 'Desserts & Sweets', ru: 'Десерты и сладости', es: 'Postres y dulces' },
  { id: 'kitchen-cooking', emoji: '🍳', en: 'Kitchen & Cooking', ru: 'Кухня и готовка', es: 'Cocina' },
  { id: 'movies', emoji: '🎬', en: 'Movies', ru: 'Фильмы', es: 'Películas' },
  { id: 'tv-shows', emoji: '📺', en: 'TV Shows', ru: 'Сериалы', es: 'Series' },
  { id: 'music', emoji: '🎵', en: 'Music & Bands', ru: 'Музыка и группы', es: 'Música y bandas' },
  { id: 'instruments', emoji: '🎸', en: 'Musical Instruments', ru: 'Музыкальные инструменты', es: 'Instrumentos musicales' },
  { id: 'celebrities', emoji: '🌟', en: 'Celebrities', ru: 'Знаменитости', es: 'Famosos' },
  { id: 'sports', emoji: '⚽', en: 'Sports', ru: 'Спорт', es: 'Deportes' },
  { id: 'fitness', emoji: '🏋️', en: 'Fitness & Gym', ru: 'Фитнес и спортзал', es: 'Gimnasio y fitness' },
  { id: 'countries-cities', emoji: '🗺️', en: 'Countries & Cities', ru: 'Страны и города', es: 'Países y ciudades' },
  { id: 'landmarks', emoji: '🗽', en: 'Landmarks', ru: 'Достопримечательности', es: 'Lugares famosos' },
  { id: 'mexico', emoji: '🇲🇽', en: 'Mexico', ru: 'Мексика', es: 'México' },
  { id: 'ukraine', emoji: '🇺🇦', en: 'Ukraine', ru: 'Украина', es: 'Ucrania' },
  { id: 'georgia', emoji: '🇬🇪', en: 'Georgia', ru: 'Грузия', es: 'Georgia' },
  { id: 'history', emoji: '🏛️', en: 'History', ru: 'История', es: 'Historia' },
  { id: 'science', emoji: '🔬', en: 'Science', ru: 'Наука', es: 'Ciencia' },
  { id: 'technology', emoji: '💻', en: 'Technology', ru: 'Технологии', es: 'Tecnología' },
  { id: 'internet-culture', emoji: '😂', en: 'Internet Culture & Memes', ru: 'Интернет-культура и мемы', es: 'Internet y memes' },
  { id: 'video-games', emoji: '🎮', en: 'Video Games', ru: 'Видеоигры', es: 'Videojuegos' },
  { id: 'books', emoji: '📚', en: 'Books', ru: 'Книги', es: 'Libros' },
  { id: 'fairy-tales', emoji: '🧚', en: 'Fairy Tales', ru: 'Сказки', es: 'Cuentos de hadas' },
  { id: 'superheroes', emoji: '🦸', en: 'Superheroes', ru: 'Супергерои', es: 'Superhéroes' },
  { id: 'cartoons', emoji: '📼', en: 'Cartoons', ru: 'Мультфильмы', es: 'Caricaturas' },
  { id: 'disney', emoji: '🏰', en: 'Disney & Pixar', ru: 'Дисней и Pixar', es: 'Disney y Pixar' },
  { id: 'professions', emoji: '👷', en: 'Professions', ru: 'Профессии', es: 'Profesiones' },
  { id: 'office-life', emoji: '🏢', en: 'Office Life', ru: 'Офисная жизнь', es: 'Vida de oficina' },
  { id: 'household-objects', emoji: '🪑', en: 'Household Objects', ru: 'Предметы быта', es: 'Objetos de la casa' },
  { id: 'tools', emoji: '🔧', en: 'Tools', ru: 'Инструменты', es: 'Herramientas' },
  { id: 'clothing', emoji: '👕', en: 'Clothing', ru: 'Одежда', es: 'Ropa' },
  { id: 'fashion-beauty', emoji: '💄', en: 'Fashion & Beauty', ru: 'Мода и красота', es: 'Moda y belleza' },
  { id: 'body-health', emoji: '🫀', en: 'Body & Health', ru: 'Тело и здоровье', es: 'Cuerpo y salud' },
  { id: 'emotions', emoji: '😊', en: 'Emotions', ru: 'Эмоции', es: 'Emociones' },
  { id: 'actions', emoji: '🏃', en: 'Actions', ru: 'Действия', es: 'Acciones' },
  { id: 'hobbies', emoji: '🧶', en: 'Hobbies', ru: 'Хобби', es: 'Pasatiempos' },
  { id: 'idioms', emoji: '💬', en: 'Idioms & Sayings', ru: 'Идиомы и поговорки', es: 'Dichos y refranes' },
  { id: 'nature-weather', emoji: '🌦️', en: 'Nature & Weather', ru: 'Природа и погода', es: 'Naturaleza y clima' },
  { id: 'beach-summer', emoji: '🏖️', en: 'Beach & Summer', ru: 'Пляж и лето', es: 'Playa y verano' },
  { id: 'winter', emoji: '❄️', en: 'Winter', ru: 'Зима', es: 'Invierno' },
  { id: 'space', emoji: '🚀', en: 'Space', ru: 'Космос', es: 'Espacio' },
  { id: 'vehicles', emoji: '🚗', en: 'Vehicles', ru: 'Транспорт', es: 'Transporte' },
  { id: 'mythology', emoji: '⚡', en: 'Mythology', ru: 'Мифология', es: 'Mitología' },
  { id: 'art', emoji: '🎨', en: 'Art & Painting', ru: 'Искусство и живопись', es: 'Arte y pintura' },
  { id: 'board-games', emoji: '♟️', en: 'Board Games', ru: 'Настольные игры', es: 'Juegos de mesa' },
  { id: 'toys-games', emoji: '🧸', en: "Toys & Kids' Games", ru: 'Игрушки и детские игры', es: 'Juguetes y juegos infantiles' },
  { id: 'school-subjects', emoji: '✏️', en: 'School Life', ru: 'Школа', es: 'La escuela' },
  { id: 'brands-logos', emoji: '🏷️', en: 'Brands & Logos', ru: 'Бренды и логотипы', es: 'Marcas y logos' },
  { id: 'holidays', emoji: '🎉', en: 'Holidays', ru: 'Праздники', es: 'Fiestas y celebraciones' },
  { id: 'weddings', emoji: '💍', en: 'Weddings', ru: 'Свадьбы', es: 'Bodas' },
  { id: 'party-drinks', emoji: '🍸', en: 'Parties & Drinks', ru: 'Вечеринки и напитки', es: 'Fiestas y bebidas' },
  { id: 'dance-theatre', emoji: '💃', en: 'Dance & Theatre', ru: 'Танцы и театр', es: 'Danza y teatro' },
  { id: 'crime-detective', emoji: '🕵️', en: 'Crime & Detective', ru: 'Детективы и преступления', es: 'Crimen y detectives' },
  { id: 'medicine', emoji: '💊', en: 'Medicine', ru: 'Медицина', es: 'Medicina' },
  { id: 'business-money', emoji: '💰', en: 'Business & Money', ru: 'Бизнес и деньги', es: 'Negocios y dinero' },
  { id: 'romance-dating', emoji: '💕', en: 'Romance & Dating', ru: 'Романтика и свидания', es: 'Romance y citas' },
  { id: 'parenting', emoji: '👶', en: 'Parenting', ru: 'Родительство', es: 'Crianza' },
  { id: 'travel', emoji: '✈️', en: 'Travel', ru: 'Путешествия', es: 'Viajes' },
  { id: 'camping', emoji: '⛺', en: 'Camping', ru: 'Кемпинг', es: 'Acampar' },
  { id: 'ocean-life', emoji: '🐠', en: 'Ocean Life', ru: 'Морская жизнь', es: 'Vida marina' },
  { id: 'dinosaurs', emoji: '🦕', en: 'Dinosaurs', ru: 'Динозавры', es: 'Dinosaurios' },
  { id: 'insects', emoji: '🐝', en: 'Insects', ru: 'Насекомые', es: 'Insectos' },
  { id: 'plants-flowers', emoji: '🌸', en: 'Plants & Flowers', ru: 'Растения и цветы', es: 'Plantas y flores' },
  { id: 'colors-shapes', emoji: '🔺', en: 'Colors & Shapes', ru: 'Цвета и формы', es: 'Colores y formas' },
  { id: 'sounds-noises', emoji: '🔊', en: 'Sounds & Noises', ru: 'Звуки и шумы', es: 'Sonidos y ruidos' },
  { id: 'smells-tastes', emoji: '👃', en: 'Smells & Tastes', ru: 'Запахи и вкусы', es: 'Olores y sabores' },
  { id: 'awkward-situations', emoji: '😬', en: 'Awkward Situations', ru: 'Неловкие ситуации', es: 'Situaciones incómodas' },
  { id: 'retro-90s', emoji: '⏪', en: '90s Nostalgia', ru: 'Ностальгия по 90-м', es: 'Nostalgia de los 90' },
  { id: 'russian-culture', emoji: '🪆', en: 'Russian Culture', ru: 'Русская культура', es: 'Cultura rusa' },
  { id: 'soviet-nostalgia', emoji: '📻', en: 'Soviet Nostalgia', ru: 'Советская ностальгия', es: 'Nostalgia soviética' },
  { id: 'anime', emoji: '🍥', en: 'Anime', ru: 'Аниме', es: 'Anime' },
  { id: 'horror', emoji: '👻', en: 'Horror', ru: 'Ужасы', es: 'Terror' },
  { id: 'luxury', emoji: '💎', en: 'Luxury', ru: 'Роскошь', es: 'Lujo' },
  { id: 'tiny-things', emoji: '📎', en: 'Tiny Things', ru: 'Крошечные вещи', es: 'Cosas diminutas' },
  { id: 'giant-things', emoji: '🦣', en: 'Giant Things', ru: 'Гигантские вещи', es: 'Cosas gigantes' },
]

export const TOPIC_BY_ID = Object.fromEntries(TOPIC_PRESETS.map(t => [t.id, t]))

export const topicName = (t, lang) => t[lang] || t.en
