// Preset topic library for pack selection (id, emoji, English/Russian display names)
export const TOPIC_PRESETS = [
  { id: 'mixed', emoji: '🎲', en: 'Mixed', ru: 'Микс' },
  { id: 'animals', emoji: '🐘', en: 'Animals', ru: 'Животные' },
  { id: 'food-drink', emoji: '🍕', en: 'Food & Drink', ru: 'Еда и напитки' },
  { id: 'movies', emoji: '🎬', en: 'Movies', ru: 'Фильмы' },
  { id: 'tv-shows', emoji: '📺', en: 'TV Shows', ru: 'Сериалы' },
  { id: 'music', emoji: '🎵', en: 'Music & Bands', ru: 'Музыка и группы' },
  { id: 'celebrities', emoji: '🌟', en: 'Celebrities', ru: 'Знаменитости' },
  { id: 'sports', emoji: '⚽', en: 'Sports', ru: 'Спорт' },
  { id: 'countries-cities', emoji: '🗺️', en: 'Countries & Cities', ru: 'Страны и города' },
  { id: 'history', emoji: '🏛️', en: 'History', ru: 'История' },
  { id: 'science', emoji: '🔬', en: 'Science', ru: 'Наука' },
  { id: 'technology', emoji: '💻', en: 'Technology', ru: 'Технологии' },
  { id: 'internet-culture', emoji: '😂', en: 'Internet Culture & Memes', ru: 'Интернет-культура и мемы' },
  { id: 'video-games', emoji: '🎮', en: 'Video Games', ru: 'Видеоигры' },
  { id: 'books', emoji: '📚', en: 'Books', ru: 'Книги' },
  { id: 'fairy-tales', emoji: '🧚', en: 'Fairy Tales', ru: 'Сказки' },
  { id: 'superheroes', emoji: '🦸', en: 'Superheroes', ru: 'Супергерои' },
  { id: 'cartoons', emoji: '📼', en: 'Cartoons', ru: 'Мультфильмы' },
  { id: 'professions', emoji: '👷', en: 'Professions', ru: 'Профессии' },
  { id: 'household-objects', emoji: '🪑', en: 'Household Objects', ru: 'Предметы быта' },
  { id: 'tools', emoji: '🔧', en: 'Tools', ru: 'Инструменты' },
  { id: 'clothing', emoji: '👕', en: 'Clothing', ru: 'Одежда' },
  { id: 'body-health', emoji: '🫀', en: 'Body & Health', ru: 'Тело и здоровье' },
  { id: 'emotions', emoji: '😊', en: 'Emotions', ru: 'Эмоции' },
  { id: 'actions', emoji: '🏃', en: 'Actions', ru: 'Действия' },
  { id: 'idioms', emoji: '💬', en: 'Idioms & Sayings', ru: 'Идиомы и поговорки' },
  { id: 'nature-weather', emoji: '🌦️', en: 'Nature & Weather', ru: 'Природа и погода' },
  { id: 'space', emoji: '🚀', en: 'Space', ru: 'Космос' },
  { id: 'vehicles', emoji: '🚗', en: 'Vehicles', ru: 'Транспорт' },
  { id: 'mythology', emoji: '⚡', en: 'Mythology', ru: 'Мифология' },
  { id: 'art', emoji: '🎨', en: 'Art & Painting', ru: 'Искусство и живопись' },
  { id: 'board-games', emoji: '♟️', en: 'Board Games', ru: 'Настольные игры' },
  { id: 'school-subjects', emoji: '✏️', en: 'School Subjects', ru: 'Школьные предметы' },
  { id: 'brands-logos', emoji: '🏷️', en: 'Brands & Logos', ru: 'Бренды и логотипы' },
  { id: 'holidays', emoji: '🎉', en: 'Holidays', ru: 'Праздники' },
  { id: 'dance-theatre', emoji: '💃', en: 'Dance & Theatre', ru: 'Танцы и театр' },
  { id: 'crime-detective', emoji: '🕵️', en: 'Crime & Detective', ru: 'Детективы и преступления' },
  { id: 'medicine', emoji: '💊', en: 'Medicine', ru: 'Медицина' },
  { id: 'business-money', emoji: '💰', en: 'Business & Money', ru: 'Бизнес и деньги' },
  { id: 'romance-dating', emoji: '💕', en: 'Romance & Dating', ru: 'Романтика и свидания' },
  { id: 'parenting', emoji: '👶', en: 'Parenting', ru: 'Родительство' },
  { id: 'travel', emoji: '✈️', en: 'Travel', ru: 'Путешествия' },
  { id: 'camping', emoji: '⛺', en: 'Camping', ru: 'Кемпинг' },
  { id: 'ocean-life', emoji: '🐠', en: 'Ocean Life', ru: 'Морская жизнь' },
  { id: 'dinosaurs', emoji: '🦕', en: 'Dinosaurs', ru: 'Динозавры' },
  { id: 'insects', emoji: '🐝', en: 'Insects', ru: 'Насекомые' },
  { id: 'plants-flowers', emoji: '🌸', en: 'Plants & Flowers', ru: 'Растения и цветы' },
  { id: 'colors-shapes', emoji: '🔺', en: 'Colors & Shapes', ru: 'Цвета и формы' },
  { id: 'sounds-noises', emoji: '🔊', en: 'Sounds & Noises', ru: 'Звуки и шумы' },
  { id: 'smells-tastes', emoji: '👃', en: 'Smells & Tastes', ru: 'Запахи и вкусы' },
  { id: 'awkward-situations', emoji: '😬', en: 'Awkward Situations', ru: 'Неловкие ситуации' },
  { id: 'retro-90s', emoji: '⏪', en: '90s Nostalgia', ru: 'Ностальгия по 90-м' },
  { id: 'russian-culture', emoji: '🪆', en: 'Russian Culture', ru: 'Русская культура' },
  { id: 'soviet-nostalgia', emoji: '📻', en: 'Soviet Nostalgia', ru: 'Советская ностальгия' },
  { id: 'anime', emoji: '🍥', en: 'Anime', ru: 'Аниме' },
  { id: 'horror', emoji: '👻', en: 'Horror', ru: 'Ужасы' },
  { id: 'luxury', emoji: '💎', en: 'Luxury', ru: 'Роскошь' },
  { id: 'tiny-things', emoji: '📎', en: 'Tiny Things', ru: 'Крошечные вещи' },
  { id: 'giant-things', emoji: '🦣', en: 'Giant Things', ru: 'Гигантские вещи' },
]

export const TOPIC_BY_ID = Object.fromEntries(TOPIC_PRESETS.map(t => [t.id, t]))
